apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-nginx-config
  namespace: xquare-prod
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      upstream grpc_backend {
          server otel-trace-reciever-be-prod:4317;
      }

      server {
          listen 80 http2;

          location / {
              grpc_pass grpc://grpc_backend;
              grpc_set_header Host $host;
              grpc_set_header X-Real-IP $remote_addr;
              grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              grpc_set_header TE "trailers";
              grpc_set_header grpc-accept-encoding "gzip";
          }

          # Error handling for gRPC
          location = /error502grpc {
              internal;
              default_type application/grpc;
              add_header content-type application/grpc;
              return 502;
          }
      }
    }
