apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc: null
          http: null
    processors:

    exporters:
      logging: null

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]