controller:
  manager:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
  tolerations:
    - effect: "NoSchedule"
      key: "xquare/platform"
      operator: "Equal"
      value: "true"

defaultVaultConnection:
  enabled: true
  address: http://vault.vault.svc.cluster.local:8200