apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Values.provisioner.name }}
spec:
  kubeletConfiguration:
    maxPods: {{ .Values.provisioner.spec.kubeletConfiguration.maxPods }}
  taints: {{ .Values.provisioner.spec.taints  | toYaml | nindent 4 }}
  labels:
    {{- range $key, $value := .Values.provisioner.spec.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  requirements:
    {{- range .Values.provisioner.spec.requirements }}
    - key: {{ .key | quote }}
      operator: {{ .operator | quote }}
      values:
        {{- range .values }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- if .Values.provisioner.spec.limits }}
  limits:
    {{- if .Values.provisioner.spec.limits.resources }}
    resources:
      cpu: {{ .Values.provisioner.spec.limits.resources.cpu }}
      memory: {{ .Values.provisioner.spec.limits.resources.memory }}
    {{- end }}
  {{- end }}
  providerRef:
    name: {{ .Values.provisioner.spec.providerRef.name }}
  ttlSecondsAfterEmpty: {{ .Values.provisioner.spec.ttlSecondsAfterEmpty }}

---

apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ .Values.awsNodeTemplate.name }}
spec:
  subnetSelector:
    karpenter.sh/discovery/xquare-v2-cluster: '*'
  securityGroupSelector:
    aws:eks:cluster-name: xquare-v2-cluster
  tags:
    karpenter.sh/discovery: xquare-v2-cluster