apiVersion: v2
name: kube-cost
description: kubecost for Kubernetes cost monitoring
type: application
version: 1.0.0
appVersion: "2.0.0"
dependencies:
  - name: cost-analyzer
    version: "2.0.0"
    repository: https://kubecost.github.io/cost-analyzer
