global:
  prometheus:
    enabled: false
    fqdn: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
  grafana:
    enabled: false
    domainName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local