global:
  prometheus:
    enabled: false
    fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  grafana:
    enabled: false
    domainName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
  kubecostToken: dGVhbXhxdWFyZUBkc20uaHMua3I=xm343yadf98

clusterController:
  enabled: true

tolerations:
  - effect: "NoSchedule"
    key: xquare/platform
    operator: "Equal"
    value: "true"