{{- range .Values.virtualServices }}
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .name }}
  namespace: istio-system
spec:
  gateways:
    - "xquare-ingressgateway"
  hosts:
    - {{ .host }}
  http:
  - corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - "*"
      allowHeaders:
        - "*"
      exposeHeaders:
        - "*"
      maxAge: "24h"
      allowCredentials: true
    route:
    - destination:
        host: {{ .destination.host }}
        port:
          number: {{ .destination.port }}
{{- end }}
