aws-node-termination-handler: 
  image:
    repository: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/node-termination-handler
    tag: "v1.0.18"
  taintNode: true
  emitKubernetesEvents: true
  logLevel: debug
  webhookURLSecretName: "nth-webhook-secret"
  webhookTemplate: "{\"text\":\"*INSTANCE INTERRUPTION NOTICE*\n- *EventID:* {{ .EventID }}\n- *InstanceId:* {{ .InstanceID }}\n- *InstanceType:* {{ .InstanceType }}- \n- *Start Time:* {{ .StartTime }}\n- *Description:* {{ .Description }}\", \"icon_emoji\":\":spot-intstance:\", \"username\":\"Node Termination Handler\" }"
  enableSpotInterruptionDraining: true
  enableScheduledEventDraining: true
  enableRebalanceMonitoring: true
  enableRebalanceDraining: true
  enableSqsTerminationDraining: false
  serviceAccount:
    create: false
    name: aws-nth
  nodeSelector:
    Karpenter: enabled
  tolerations:
    - operator: "Exists"
