apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: {{ .Values.istioOperator.profile }}
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    {{- range .Values.istioOperator.extensionProviders }}
      - name: {{ .name }}
        envoyExtAuthzGrpc:
          service: {{ .envoyExtAuthzGrpc.service }}
          port: {{ .envoyExtAuthzGrpc.port }}
    {{- end }}
  components:
    pilot:
      k8s:
        {{- with .Values.nodeSelector }}
        nodeSelector: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations: {{ toYaml . | nindent 10 }}
        {{- end }}
        hpaSpec:
          minReplicas: 2
          maxReplicas: 3
        resources:
          requests:
            cpu: 189m
            memory: 250Mi
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          service.istio.io/canonical-name: istio-ingressgateway
        k8s:
          hpaSpec:
            minReplicas: {{ .Values.istioOperator.hpaSpec.minReplicas }}
            maxReplicas: {{ .Values.istioOperator.hpaSpec.maxReplicas }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          service:
            type: LoadBalancer
            ports:
            {{- range .Values.istioOperator.servicePorts }}
            - name: {{ .name }}
              port: {{ .port }}
              targetPort: {{ .targetPort }}
            {{- end }}
            externalTrafficPolicy: {{ .Values.istioOperator.service.externalTrafficPolicy }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: 30m
              memory: 180Mi

    egressGateways:
      - name: istio-egressgateway
        namespace: istio-system
        enabled: true
        label:
          service.istio.io/canonical-name: istio-egressgateway
        k8s:
          hpaSpec:  
            minReplicas: {{ .Values.istioOperator.hpaSpec.minReplicas }}
            maxReplicas: {{ .Values.istioOperator.hpaSpec.maxReplicas }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: 10m
              memory: 80Mi
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        type: ClusterIP
    global:
      {{- with .Values.nodeSelector }}
      defaultNodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      defaultTolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
  unvalidatedValues:
    {{- with .Values.nodeSelector }}
    nodeSelector: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}
