global:
  injector:
    enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 256Mi
        cpu: 250m

server:
  enabled: true
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 400m

ui:
  enabled: true
  serviceType: "ClusterIP"
  externalPort: 8200
