apiVersion: v2
appVersion: 1.114.0
name: opencost
description: OpenCost and OpenCost UI
type: application
version: 2.0.1
dependencies:
  - name: prometheus-opencost-exporter
    version: 0.1.2
    repository: https://prometheus-community.github.io/helm-charts
