serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/opencost-role"
  automountServiceAccountToken: true

service:
  enabled: true
  type: ClusterIP

rbac:
  enabled: true

opencost:
  exporter:
    apiPort: 9003
    replicas: 1
    resources:
      requests:
        cpu: '10m'
        memory: '55Mi'
      limits:
        memory: '1Gi'
    startupProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 30
    livenessProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 20
      failureThreshold: 3
    readinessProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
    env:
      - name: PROMETHEUS_SERVER_ENDPOINT
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - name: CLUSTER_ID
        value: "xquare-v3-cluster"
      - name: LOG_LEVEL
        value: "debug"

  dataRetention:
    dailyResolutionDays: 15

  cloudCost:
    enabled: true
    refreshRateHours: 6
    runWindowDays: 3
    monthToDateInterval: 6
    queryWindowDays: 7

  metrics:
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      scrapeInterval: 30s
      scrapeTimeout: 10s
      honorLabels: true

  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090