opencost:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/opencost-role"
    automountServiceAccountToken: true

  networkPolicies:
    enabled: false

  service:
    enabled: true
    type: ClusterIP

  rbac:
    enabled: true

  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090
    external:
      enabled: false

  exporter:
    extraEnv:
      PROMETHEUS_SERVER_ENDPOINT: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      CLUSTER_ID: "xquare-v3-cluster"
      LOG_LEVEL: "debug"

    env:
      - name: PROMETHEUS_SERVER_ENDPOINT
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - name: CLUSTER_ID
        value: "xquare-v3-cluster"
      - name: LOG_LEVEL
        value: "debug"

  metrics:
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      scrapeInterval: 30s
      honorLabels: true

    kubeStateMetrics:
      emitKsmV1Metrics: true