plugins:
  enabled: false
  install:
    enabled: true
    fullImageName: curlimages/curl:latest
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
  folder: /opt/opencost/plugin
  configs:

serviceAccount:
  create: true
  annotations: "arn:aws:iam::786584124104:role/opencost-role"
  automountServiceAccountToken: true

networkPolicies:
  enabled: false

  prometheus:
    namespace: monitoring
    port: 9090
    labels:
      app.kubernetes.io/name: prometheus

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

service:
  enabled: true
  annotations: {}
  labels: {}
  type: ClusterIP

rbac:
  enabled: true

opencost:
  exporter:
    apiPort: 9003
    replicas: 1
    resources:
      requests:
        cpu: '10m'
        memory: '55Mi'
      limits:
        memory: '1Gi'
    startupProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 30
    livenessProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 20
      failureThreshold: 3
    readinessProbe:
      enabled: true
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
    securityContext: {}
    csv_path: ""

    persistence:
      enabled: false
      annotations: {}
      accessMode: ""
      storageClass: ""
      size: ""

    aws:
      secret_access_key: ""
      access_key_id: ""
    extraVolumeMounts: []
    env: []
    extraEnv: {}
  customPricing:
    enabled: false
    configmapName: custom-pricing-model
    configPath: /tmp/custom-config
    createConfigmap: true
    provider: custom
    costModel:
      description: Modified pricing configuration.
      CPU: 1.25
      spotCPU: 0.006655
      RAM: 0.50
      spotRAM: 0.000892
      GPU: 0.95
      storage: 0.25
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.12

  dataRetention:
    dailyResolutionDays: 15

  carbonCost:
    enabled: false

  cloudCost:
    enabled: true
    refreshRateHours: 6
    runWindowDays: 3
    monthToDateInterval: 6
    queryWindowDays: 7

  metrics:
    kubeStateMetrics:
      emitPodAnnotations: ~
      emitNamespaceAnnotations: ~
      emitKsmV1Metrics: ~
      emitKsmV1MetricsOnly: ~

    serviceMonitor:
      enabled: false
      additionalLabels: {}
      namespace: ""
      scrapeInterval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings: []
      metricRelabelings: []
      extraEndpoints: []
      scheme: http
      tlsConfig: {}

    config:
      enabled: false
      configmapName: custom-metrics
      disabledMetrics: []

  prometheus:
    external:
      enabled: true
      url: "https://prometheus.xquare.app"
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090