opencost:
  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090
  exporter:
    resources:
      requests:
        cpu: '50m'
        memory: '128Mi'
      limits:
        cpu: '100m'
        memory: '512Mi'

  dataRetention:
    dailyResolutionDays: 30

rbac:
  enabled: true

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/opencost-role"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true