name: ext-authz
image: 471407337433.dkr.ecr.ap-northeast-2.amazonaws.com/envoy-middleware-be-prod:prod-bea3f29b5bff852sxzc2f7q373f022d15qz

nodeSelector:
  Karpenter: enabled
  
tolerations:
- effect: "PreferNoSchedule"
  key: xquare/platform
  operator: "Equal"
  value: "true"
