name: ext-authz
image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/envoy-middleware:prod-cc95ec383ccdb4e3aafc8e7eb3de7f649bb7b7db

nodeSelector:
  Karpenter: enabled
  
tolerations:
- effect: "NoSchedule"
  key: xquare/platform
  operator: "Equal"
  value: "true"
