name: ext-authz
image: 471407337433.dkr.ecr.ap-northeast-2.amazonaws.com/envoy-middleware-be-prod:latest

nodeSelector:
  Karpenter: enabled
  
tolerations:
- effect: "PreferNoSchedule"
  key: xquare/server
  operator: "Equal"
  value: "true"
