strimzi-kafka-operator:
  fullnameOverride: kafka-operator
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      external:
        type: route
  zookeeper:
    replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
  tolerations:
    - key: "xquare/platform"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  resources:
    limits:
      memory: 384Mi
      cpu: 1000m
    requests:
      memory: 384Mi
      cpu: 120m