apiVersion: v1
kind: Pod
metadata:
  name: over-provisioning-pod
  namespace: gocd
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.2
  priorityClassName: system-node-critical
  tolerations:
    - key: "xquare/build-server"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "Karpenter"
                operator: In
                values: [ "enabled" ]