opentelemetry-operator:
  manager:
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
  tolerations:
    - effect: "NoSchedule"
      key: xquare/platform
      operator: "Equal"
      value: "true"

opentelemetry-collector:
  tolerations:
    - effect: "NoSchedule"
      key: xquare/platform
      operator: "Equal"
      value: "true"
  image:
    repository: "otel/opentelemetry-collector-contrib"
  mode: "deployment"
  config:
    exporters:
      otlp/tempo:
        endpoint: grafana-tempo-distributor-discovery.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      otlp/springboot:
        endpoint: xquare-infra-prod.xquare-prod.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 1s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        traces:
          exporters:
            - otlp/tempo
            - otlp/springboot
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - prometheus