opentelemetry-collector:
  ports:
    metrics:
      enabled: true
      containerPort: 8889
      servicePort: 8889
      protocol: TCP
  tolerations:
    - operator: "Exists"
  image:
    repository: "otel/opentelemetry-collector-contrib"
  mode: "daemonset"
  extraEnvsFrom:
    - secretRef:
        name: datadog-secret
  config:
    connectors:
      datadog/connector:
    exporters:
      datadog/exporter:
        api:
          site: us5.datadoghq.com
          key: ${env:DD_API_KEY}
      otlp/go:
        endpoint: grpc-nginx-service.xquare-prod.svc.cluster.local:80
        tls:
          insecure: true
        compression: none
      prometheus:
        endpoint: "0.0.0.0:8889"
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 1s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      hostmetrics:
        collection_interval: 10s
        scrapers:
          paging:
            metrics:
              system.paging.utilization:
                enabled: true
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          disk: {}
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          load: {}
          memory: {}
          network: {}
          processes: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otelcol'
              scrape_interval: 10s
              static_configs:
                - targets: [ '0.0.0.0:8888' ]
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/go
            - datadog/exporter
        metrics:
          receivers:
            - otlp
            - prometheus
            - hostmetrics
          processors:
            - batch
          exporters:
            - datadog/exporter
        logs:
          receivers:
            - otlp
            - filelog   # "filelo" → "filelog"
          processors:
            - batch
          exporters:
            - datadog/exporter
