opentelemetry-collector:
  ports:
    metrics:
      enabled: true
      containerPort: 8889
      servicePort: 8889
      protocol: TCP
  mode: "daemonset"
  tolerations:
    - key: "xquare/server"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "xquare/critical_service"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  image:
    repository: "otel/opentelemetry-collector-contrib"
  extraEnvsFrom:
    - secretRef:
        name: datadog-secret
  config:
    exporters:
      datadog/exporter:
        api:
          site: us5.datadoghq.com
          key: ${env:DD_API_KEY}
        apm_stats_enabled: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 1s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      hostmetrics:
        collection_interval: 10s
        scrapers:
          paging:
            metrics:
              system.paging.utilization:
                enabled: true
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          disk: {}
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          load: {}
          memory: {}
          network: {}
          processes: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otelcol'
              scrape_interval: 10s
              static_configs:
                - targets: [ '0.0.0.0:8888' ]
      filelog:
        include:
          - /var/log/**/*.log
        start_at: beginning
        poll_interval: 500ms
        operators:
          - id: json_parser
            type: json_parser
            parse_from: body
          - id: trace_parser
            type: trace_parser
            trace_id:
              parse_from: attributes.trace_id
            span_id:
              parse_from: attributes.span_id
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ datadog/exporter ]
        metrics:
          receivers: [ otlp, prometheus, hostmetrics ]
          processors: [ batch ]
          exporters: [ datadog/exporter ]
        logs:
          receivers: [ otlp, filelog ]
          processors: [ batch ]
          exporters: [ datadog/exporter ]

opentelemetry-operator:
  manager:
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
  tolerations:
    - effect: "NoSchedule"
      key: xquare/platform
      operator: "Equal"
      value: "true"