opentelemetry-operator:
  manager:
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
  tolerations:
    - effect: "NoSchedule"
      key: xquare/platform
      operator: "Equal"
      value: "true"

opentelemetry-collector:
  ports:
    metrics:
      # The metrics port is disabled by default. However you need to enable the port
      # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
      enabled: true
      containerPort: 8889
      servicePort: 8889
      protocol: TCP
  tolerations:
    - operator: "Exists"
  image:
    repository: "otel/opentelemetry-collector-contrib"
  mode: "daemonset"
  config:
    exporters:
      otlp/tempo:
        endpoint: grafana-tempo-distributor-discovery.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      otlp/go:
        endpoint: otel-trace-reciever-be-prod.xquare-prod.svc.cluster.local:4317
        insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 1s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        traces:
          exporters:
            - otlp/tempo
            - otlp/go
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          receivers:
            - otlp
            - prometheus
          processors:
            - memory_limiter
            - batch
          exporters:
            - prometheus