provisioner:
  name: xquare
  spec:
    taints:
    - key: "xquare/server"
      value: "true"
      effect: "PreferNoSchedule"
    labels:
      Karpenter: enabled    
    kubeletConfiguration:
      maxPods: 110
    requirements:
      - key: kubernetes.io/os
        operator: In
        values:
          - "linux"
      - key: "karpenter.sh/capacity-type"
        operator: In
        values:
          - "spot"
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: In
        values: ["2"]
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]
      - key: kubernetes.io/arch	
        operator: In	
        values:	
          - amd64
    providerRef:
      name: xquare
    ttlSecondsAfterEmpty: 20
awsNodeTemplate:
  name: xquare