apiVersion: v2
name: datadog-operator
version: 1.0.3
appVersion: 1.3.0
description: Datadog Operator
dependencies:
  - name: datadog-operator
    version: 1.4.1
    repository: https://helm.datadoghq.com