apiVersion: v2
name: datadog-operator
version: 1.0.2
appVersion: 1.3.0
description: Datadog Operator
dependencies:
  - name: datadog-crds
    version: "=1.3.0"
    alias: datadogCRDs
    repository: https://helm.datadoghq.com
    condition: installCRDs
    tags:
      - install-crds
  - name: datadog-operator
    version: 1.4.1
    repository: https://helm.datadoghq.com