datadog-operator:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: us5.datadoghq.com
  datadogCRDs:
    crds:
      # datadogCRDs.crds.datadogAgents -- Set to true to deploy the DatadogAgents CRD
      datadogAgents: true
      # datadogCRDs.crds.datadogMetrics -- Set to true to deploy the DatadogMetrics CRD
      datadogMetrics: true
      # datadogCRDs.crds.datadogPodAutoscalers -- Set to true to deploy the DatadogPodAutoscalers CRD
      datadogPodAutoscalers: true
      # datadogCRDs.crds.datadogMonitors -- Set to true to deploy the DatadogMonitors CRD
      datadogMonitors: true
      # datadogCRDs.crds.datadogSLOs -- Set to true to deploy the DatadogSLO CRD
      datadogSLOs: false
      # datadogCRDs.crds.datadogDashboards -- Set to true to deploy the DatadogDashboard CRD
      datadogDashboards: true
      # datadogCRDs.crds.datadogGenericResources -- Set to true to deploy the DatadogGenericResource CRD
      datadogGenericResources: false
  datadogDashboard:
    # datadogDashboard.enabled -- Enables the Datadog Dashboard controller
    enabled: true