datadog-operator:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
  datadogCRDs:
    crds:
      # datadogCRDs.crds.datadogAgents -- Set to true to deploy the DatadogAgents CRD
      datadogAgents: true
      # datadogCRDs.crds.datadogMetrics -- Set to true to deploy the DatadogMetrics CRD
      datadogMetrics: true
      # datadogCRDs.crds.datadogPodAutoscalers -- Set to true to deploy the DatadogPodAutoscalers CRD
      datadogPodAutoscalers: true
      # datadogCRDs.crds.datadogMonitors -- Set to true to deploy the DatadogMonitors CRD
      datadogMonitors: true
      # datadogCRDs.crds.datadogSLOs -- Set to true to deploy the DatadogSLO CRD
      datadogSLOs: false
      # datadogCRDs.crds.datadogDashboards -- Set to true to deploy the DatadogDashboard CRD
      datadogDashboards: true
      # datadogCRDs.crds.datadogGenericResources -- Set to true to deploy the DatadogGenericResource CRD
      datadogGenericResources: false
  datadogDashboard:
    # datadogDashboard.enabled -- Enables the Datadog Dashboard controller
    enabled: true
  datadogMonitor:
    # datadogMonitor.enabled -- Enables the Datadog Monitor controller
    enabled: true
datadog:
  agents:
    image:
      repository: "gcr.io/datadoghq/agent"
      tag: "7.65.0-full"
      pullPolicy: "Always"
    datadog:
      apiKeyExistingSecret: "datadog-secret"
      otelCollector:
        enabled: true
        ports:
          - containerPort: 4317
            hostPort: 4317
            name: "otel-grpc"
          - containerPort: 4318
            hostPort: 4318
            name: "otel-http"
      site: "datadoghq.com"
      apm:
        instrumentation:
          enabled: true
          targets:
            - name: "default-target"
              ddTraceVersions:
                java: "1"
                python: "3"
                js: "5"
                php: "1"
                dotnet: "3"
      logs:
        enabled: true
        containerCollectAll: true
      asm:
        threats:
          enabled: true
        sca:
          enabled: true
        iast:
          enabled: true
      securityAgent:
        runtime:
          enabled: true
        compliance:
          enabled: true
      sbom:
        containerImage:
          enabled: true
        host:
          enabled: true
      serviceMonitoring:
        enabled: true
      networkMonitoring:
        enabled: true
