apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: equus-kafka-cluster
  namespace: kafka
spec:
  kafka:
    tolerations:
      - key: "xquare/critical"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
          storageClass: gp2
  zookeeper:
    tolerations:
      - key: "xquare/critical"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      storageClass: gp2
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: equus-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: equus-kafka-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
