apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: equus-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: ClusterIP
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.0"
    storage:
      type: persistent-claim
      size: 10Gi
      class: standard
      deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      class: standard
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: equus-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: equus-kafka-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
