apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-cp-kafka-headless:9092"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: "connect"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: "http://kafka-cp-kafka-connect:8083"
            - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
              value: "kafka-cp-ksql-server:8088"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://kafka-cp-schema-registry:8081"

            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$(KAFKA_PROPERTY_APIKEY)\" password=\"$(KAFKA_PROPERTY_APISECRET)\";"

            - name: KAFKA_PROPERTY_APIKEY
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-secrets
                  key: apiKey
            - name: KAFKA_PROPERTY_APISECRET
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-secrets
                  key: apiSecret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"