apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: xquare-nodeclass-default
spec:
  role: "KarpenterNodeRole-xquare-v3-cluster"
  amiFamily: AL2
  amiSelectorTerms:
    - id: ami-055a279ce49cf8270
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: xquare-v3-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/xquare-v3-cluster: '*'
  tags:
    karpenter.sh/discovery: xquare-v3-cluster
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 25Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  kubelet:
    maxPods: 110