{{- range .Values.nodepools.services }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    expireAfter: 720h
    consolidateAfter: 5m
  template:
    metadata:
      labels:
        {{- range $key, $value := .spec.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      nodeClassRef:
        name: xquare-nodeclass

      taints: {{ .spec.taints | toYaml | nindent 8 }}
      requirements:
        {{- range .spec.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator | quote }}
          values:
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
{{ end }}