apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: xquare-nodeclass
spec:
  role: "KarpenterNodeRole-xquare-v2-cluster"
  amiFamily: AL2
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: xquare-v2-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/xquare-v2-cluster: '*'
  tags:
    karpenter.sh/discovery: xquare-v2-cluster