{{- range .Values.nodepools.services }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        {{- range $key, $value := .spec.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      terminationGracePeriod: 5m
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: xquare-nodeclass-default
      taints: {{ .spec.taints | toYaml | nindent 8 }}
      requirements:
        {{- range .spec.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator | quote }}
          values:
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
{{ end }}