{{ range .Values.nodepools.services }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .name }}-nodepool
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    metadata:
      labels:
        {{- range $key, $value := .spec.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      nodeClassRef:
        name: {{ .name }}-nodeclass
      taints: {{ .spec.taints | toYaml | nindent 8 }}
      requirements:
        {{- range .spec.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator | quote }}
          values:
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      kubelet:
        maxPods: {{ .spec.kubeletConfiguration.maxPods }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .name }}-nodeclass
spec:
  role: "KarpenterNodeRole-xquare-v2-cluster"
  amiFamily: AL2
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: xquare-v2-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/xquare-v2-cluster: '*'
  tags:
    karpenter.sh/discovery: xquare-v2-cluster
{{ end }}
