apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.provisioner.name }}-nodepool
spec:
  role: KarpenterIRSA-xquare-v2-cluster-20230912025141421600000001
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.provisioner.spec.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      nodeClassRef:
        name: {{ .Values.provisioner.name }}-nodeclass
      taints: {{ .Values.provisioner.spec.taints | toYaml | nindent 8 }}
      requirements:
        {{- range .Values.provisioner.spec.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator | quote }}
          values:
          {{- range .values }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      kubelet:
        maxPods: {{ .Values.provisioner.spec.kubeletConfiguration.maxPods }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.provisioner.name }}-nodeclass
spec:
  # Required, resolves a default ami and userdata
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/xquare-v2-cluster: '*'

  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: xquare-v2-cluster
  tags:
    karpenter.sh/discovery: xquare-v2-cluster