apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: xquare-nodeclass-io2
spec:
  role: "KarpenterNodeRole-xquare-v3-cluster"
  amiFamily: AL2
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: xquare-v3-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/xquare-v3-cluster: '*'
  tags:
    karpenter.sh/discovery: xquare-v3-cluster
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        iops: 10000
        encrypted: true
        deleteOnTermination: true