{{- range .Values.nodepools.services }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    expireAfter: 720h
    consolidationAfter: 5m
  template:
    metadata:
      labels:
        {{- range $key, $value := .spec.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      nodeClassRef:
        name: xquare-nodeclass-default

      taints: {{ .spec.taints | toYaml | nindent 8 }}
      requirements:
        {{- range .spec.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator | quote }}
          values:
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      kubelet:
        evictionSoft:
          memory.available: 1000Mi
        evictionSoftGracePeriod:
          memory.available: 1m
        maxPods: {{ .spec.kubeletConfiguration.maxPods }}
{{ end }}