{{- range .Values.monitors }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
spec:
  query: "{{ .query }}"
  type: "{{ .type }}"
  name: "{{ .name }}"
  message: "{{ .message }}"
  {{- if .tags }}
  tags:
  {{- range .tags }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- if .priority }}
  priority: {{ .priority }}
  {{- end }}
  options:
    {{- if .options }}
    {{- if .options.evaluationDelay }}
    evaluationDelay: {{ .options.evaluationDelay }}
    {{- end }}
    includeTags: {{ .options.includeTags | default true }}
    locked: {{ .options.locked | default false }}
    {{- if .options.newGroupDelay }}
    newGroupDelay: {{ .options.newGroupDelay }}
    {{- end }}
    notifyNoData: {{ .options.notifyNoData | default false }}
    {{- if .options.noDataTimeframe }}
    noDataTimeframe: {{ .options.noDataTimeframe }}
    {{- end }}
    {{- if .options.renotifyInterval }}
    renotifyInterval: {{ .options.renotifyInterval }}
    {{- end }}
    {{- if .options.thresholds }}
    thresholds:
      {{- if .options.thresholds.critical }}
      critical: "{{ .options.thresholds.critical }}"
      {{- end }}
      {{- if .options.thresholds.warning }}
      warning: "{{ .options.thresholds.warning }}"
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}