gocd:
  server:
    toleration:
      - effect: "NoSchedule"
        key: xquare/server
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/test
        operator: "Equal"
        value: "true"
    ingress:
      enabled: false
    service:
      type: "ClusterIP"
  agent:
    toleration:
      - effect: "NoSchedule"
        key: xquare/server
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/test
        operator: "Equal"
        value: "true"