gocd:
  server:
    toleration:
      - effect: "NoSchedule"
        key: xquare/server
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/test
        operator: "Equal"
        value: "true"
    ingress:
      enabled: false
    service:
      type: "ClusterIP"
    env:
      extraEnvVars:
        - name: GOCD_PLUGIN_INSTALL_gocd-yaml-config-plugin
          value: https://github.com/tomzo/gocd-yaml-config-plugin/releases/download/v1.0.0-364/yaml-config-plugin-1.0.0-364.jar
        - name: GOCD_PLUGIN_INSTALL_docker-elastic-agents-plugin
          value: https://github.com/gocd-contrib/docker-elastic-agents-plugin/releases/download/v3.3.0-458/docker-elastic-agents-3.3.0-458.jar
  agent:
    persistence:
      enabled: true
      extraVolumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      extraVolumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    image:
      repository: gocd/gocd-agent-docker-dind
      tag: v24.2.0
      pullPolicy: Always
    replicaCount: 1
    toleration:
      - effect: "NoSchedule"
        key: xquare/server
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
      - effect: "NoSchedule"
        key: xquare/test
        operator: "Equal"
        value: "true"
