psmdb-db:
  replsets:
    rs0:
      size: 3
      expose:
        enabled: true
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      resources:
        requests:
          cpu: "60m"
          memory: "600Mi"
      volumeSpec:
        pvc:
          resources:
            requests:
              storage: 55Gi
  sharding:
    configrs:
      resources:
        requests:
          cpu: "80m"
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
    mongos:
      size: 1
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      expose:
        enabled: true
        exposeType: LoadBalancer
      resources:
        rqeuests:
          cpu: "300m"
          memory: "80Mi"

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongo-admin
        key: password
      roles:
        - name: root
          db: admin
    - name: dsm-repo
      db: dsm-repo
      passwordSecretRef:
        name: dsm-repo
        key: password
      roles:
        - name: dbOwner
          db: dsm-repo
  backup:
    enabled: false
    storages:
      s3-ap-northeast-2:
        type: s3
        s3:
          bucket: xquare-mongodb-backup
          retryer:
            numMaxRetries: 3
            minRetryDelay: 30ms
            maxRetryDelay: 5m
          region: ap-northeast-2
          prefix: ""
          uploadPartSize: 10485760
          maxUploadParts: 10000
          storageClass: STANDARD
      volumeMounts:
        - mountPath: /mnt/nfs/
          name: backup-nfs

prometheus-mongodb-exporter:
  existingSecret:
    name: "mongodb-secret"
    key: "mongodb-uri"
  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: prometheus-stack
  extraArgs:
    - --collector.diagnosticdata
    - --discovering-mode
    - --compatible-mode
    - --collect-all
    - --collector.collstats-limit=0
    - --log.level=debug
