mongodb:
  architecture: standalone

  useStatefulSet: true

  auth:
    enabled: false

  persistence:
    enabled: true
    storageClass: "gp2"
    accessModes:
      - ReadWriteOnce
    size: 40Gi

  service:
    type: ClusterIP
    port: 27017
    portName: mongodb

  tolerations:
    - effect: "NoSchedule"
      key: xquare/platform
      operator: "Equal"
      value: "true"
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 6Gi