argo-workflows:
  server:
    enabled: true
    baseHref: /
    authModes:
      - sso
    secure: false

    executor:
      workflowTaskResults: true
    sso:
      enabled: true
      issuer: "https://dex.xquare.app"
      clientId:
        name: "argo-workflow-sso"
        key: "client-id"
      clientSecret:
        name: "argo-workflow-sso"
        key: "client-secret"
      redirectUrl: "https://argo-workflows.xquare.app/oauth2/callback"
      rbac:
        enabled: false
      secretWhitelist: []
      scopes: ["openid", "profile", "email", "groups"]
      sessionExpiry: "12h"
      customGroupClaimName: "groups"
      filterGroupsRegex:
        - "team-xquare:DevOps"

#    extraArgs:
#      - --auth-mode=sso
#      - --auth-mode=client

    resources:
      requests:
        cpu: 32m
        memory: 256Mi

    tolerations:
      - key: "xquare/platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  controller:
    tolerations:
      - key: "xquare/platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

    resources:
      requests:
        cpu: 32m
        memory: 256Mi
