psmdb-db:
  replsets:
    rs0:
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      volumeSpec:
        pvc:
          resources:
            requests:
              storage: 3Gi
      resources:
        limits:
          cpu: "300m"
          memory: "2G"
        requests:
          cpu: "300m"
          memory: "2G"
  sharding:
    configrs:
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
    mongos:
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      expose:
        exposeType: LoadBalancer

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongo-admin
        key: password
      roles:
        - name: root
          db: admin
    - name: dsm-repo
      db: dsm-repo
      passwordSecretRef:
        name: dsm-repo
        key: password
      roles:
        - name: dbOwner
          db: dsm-repo
  backup:
    enabled: false
    storages:
      s3-ap-northeast-2:
        type: s3
    tasks:
      - name: daily-s3-us-west
        enabled: true
        schedule: "0 0 * * *"
        keep: 3
        storageName: s3-us-west
        compressionType: gzip