psmdb-db:
  replsets:
    rs0:
      expose:
        enabled: true
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      volumeSpec:
        pvc:
          resources:
            requests:
              storage: 40Gi
      resources:
        limits:
          cpu: "600m"
          memory: "5G"
        requests:
          cpu: "600m"
          memory: "5G"
  sharding:
    configrs:
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
    mongos:
      size: 1
      tolerations:
        - effect: "NoSchedule"
          key: xquare/database
          operator: "Equal"
          value: "true"
      expose:
        exposeType: LoadBalancer
      resources:
        limits:
          cpu: "700m"
          memory: "3G"
        requests:
          cpu: "700m"
          memory: "3G"

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongo-admin
        key: password
      roles:
        - name: root
          db: admin
    - name: dsm-repo
      db: dsm-repo
      passwordSecretRef:
        name: dsm-repo
        key: password
      roles:
        - name: dbOwner
          db: dsm-repo
  backup:
    enabled: false
    storages:
      s3-ap-northeast-2:
        type: s3
    tasks:
      - name: daily-s3-us-west
        enabled: true
        schedule: "0 0 * * *"
        keep: 3
        storageName: s3-us-west
        compressionType: gzip

prometheus-mongodb-exporter:
  existingSecret:
    name: "mongodb-secret"
    key: "mongodb-uri"
  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: prometheus-stack
  extraArgs:
    - --collector.diagnosticdata
    - --discovering-mode
    - --compatible-mode
    - --collect-all
    - --collector.collstats-limit=0
    - --log.level=debug
