dex:
  config:
    issuer: https://dex.xquare.app
    logger:
      level: debug
    storage:
      type: memory
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true 
    staticClients:
    - id: xquare  
      name: 'xquare'
      redirectURIs:
        - 'https://dex-login.xquare.app/callback'
        - 'https://dex-login.xquare.app/callback/xquare'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    - id: argocd
      name: 'argocd'
      redirectURIs:
        - 'https://argo-cd.xquare.app/api/dex/callback'
        - 'https://argo-cd.xquare.app/auth/callback'
      secret: DIKHZYN1kolN7d6
    - id: grafana
      redirectURIs:
      - 'https://grafana.xquare.app/login/generic_oauth'
      name: 'grafana'
      secret: wnZOOiLE6rwwDK2
    connectors:
    - type: github
      id: github
      name: GitHub
      scopes: ["openid", "profile", "email", "offline_access", "groups"]
      teamNameField: slug
      useLoginAsID: true
      config:
        clientID: d486635d82817cb24ce9
        clientSecret: 792b92a7326af17adeed34241ae95bbd98c1785a
        redirectURI: 'https://dex.xquare.app/callback'
        loadAllGroups: true
        orgs:
          - name: team-xquare
            teams:
            - DevOps
            - backend
          - name: mukgen
          - name: heiiwrd98
          - name: team-aliens
          - name: MaeumgaGym
            teams:
            - backend
          - name: Team-jeong-ho-kim
  requests:
    cpu: 1m
    memory: 8Mi
