ingressGateway:
  servers:
  - hosts:
      - '*.xquare.app'
    port:
      name: https-xquare
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: xquare-cert
  - hosts:
      - '*.dsm-pick.com'
    port:
      name: https-pick
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: pick-cert
  - hosts:
      - '*.dsm-repo.com'
    port:
      name: https-repo
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: repo-cert
  - hosts:
      - '*.dms-dsm.com'
    port:
      name: https-dms
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: dms-cert
  - hosts:
      - '*.entrydsm.hs.kr'
    port:
      name: https-entrydsm
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: entrydsm-cert

egressGateway:
  servers:
  - name: xquare-mysql
    protocol: TCP 
    host: "xquare-db.ctvh9cegfpii.ap-northeast-2.rds.amazonaws.com" # "mysql.xquare.app"
    port: 3306
  - name: xquare-redis
    protocol: TCP 
    host: "xquare-redis.kfd2wu.0001.apn2.cache.amazonaws.com" # "redis.xquare.app"
    port: 6379
  - name: repo-mariadb
    protocol: TCP 
    host: "mariadb.dsm-repo.com"
    port: 3316
  - name: repo-mongodb
    protocol: TCP 
    host: "mongodb.dsm-repo.com"
    port: 27017

virtualServices:
  - name: argocd-server
    host: argo-cd.xquare.app
    destination:
      host: argocd-server.argocd.svc.cluster.local
      port: 80
  - name: kiali-server
    host: kiali.xquare.app
    destination:
      host: kiali.istio-system.svc.cluster.local
      port: 20001
  - name: jaeger-server
    host: jaeger.xquare.app
    destination:
      host: tracing.istio-system.svc.cluster.local
      port: 80
  - name: grafana-server
    host: grafana.xquare.app
    destination:
      host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
      port: 80
  - name: dex-server
    host: dex.xquare.app
    destination:
      host: dex.dex.svc.cluster.local
      port: 5556
  - name: dex-login-server
    host: dex-login.xquare.app
    destination:
      host: dex-k8s-authenticator.dex.svc.cluster.local
      port: 5555
  - name: thanos-server
    host: thanos.xquare.app
    destination:
      host: thanos-query-frontend.monitoring.svc.cluster.local
      port: 9090
  - name: thanos-store-server
    host: thanos-store.xquare.app
    destination:
      host: thanos-storegateway.monitoring.svc.cluster.local
      port: 9090
  - name: loki-server
    host: loki.xquare.app
    destination:
      host: loki-gateway.monitoring.svc.cluster.local
      port: 80
  - name: prometeus-server
    host: prometheus.xquare.app
    destination:
      host: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
      port: 9090
  - name: vault-ui
    host: vault.xquare.app
    destination:
      host: vault-ui.vault.svc.cluster.local
      port: 8200
  - name: maeumgagym-prow-hook-server
    host: maeumgagym-hook.xquare.app
    destination:
      host: hook.prow.svc.cluster.local
      port: 8888
  - name: grafana-tempo
    host: grafana-tempo.xquare.app
    destination:
      host: grafana-tempo-query-frontend-discovery.monitoring.svc.cluster.local
      port: 3100
  - name: gocd
    host: gocd.xquare.app
    destination:
      host: gocd-server.gocd.svc.cluster.local
      port: 8153
  - name: equus-stag-kafka
    host: equus-stag-kafka.xquare.app
    destination:
      host: equus-stag-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local
      port: 9092
  - name: grafana-tempo-distributor
    host: grafana-tempo-distributor.xquare.app
    destination:
      host: grafana-tempo-distributor-discovery.monitoring.svc.cluster.local
      port: 4317
addons:
  jeager:
    enable: false
  kiali:
    enable: true
    prometheusUrl: http://thanos-query.monitoring.svc.cluster.local:9090
    thanos_proxy:
      enabled: true
      retention_period: "7d" 
      scrape_interval: "30s" 

nodeSelector:
  Karpenter: enabled
  
tolerations:
- effect: "NoSchedule"
  key: xquare/platform
  operator: "Equal"
  value: "true"
