{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-prod
  namespace: {{ $clubname }}-prod
spec:
  signals:
    - traces
    - metrics
    - logs
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-stag
  namespace: {{ $clubname }}-stag
spec:
  signals:
    - traces
    - metrics
    - logs
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
{{- end }}
