{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-prod
  namespace: {{ $clubname }}-prod
spec:
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.32.0
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-stag
  namespace: {{ $clubname }}-stag
spec:
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.32.0
{{- end }}