{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-stag
  namespace: {{ $clubname }}-stag
spec:
  exporter:
    endpoint: "http://0.0.0.0:4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $clubname }}-prod
  namespace: {{ $clubname }}-stag
spec:
  exporter:
    endpoint: "http://0.0.0.0:4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
{{- end }}