{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $clubname }}-stag
  labels:
    name: {{ $clubname }}-stag
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $clubname }}-prod
  labels:
    name: {{ $clubname }}-prod
    istio-injection: enabled
{{- end }}