karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam:::role/KarpenterControllerRole-xquare-v2-cluster"
  aws:
    defaultInstanceProfile: ""
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 16m
        memory: 244Mi
  settings:
    clusterName: "xquare-v2-cluster"