karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  clusterName: ""
  clusterEndpoint: ""
  aws:
    defaultInstanceProfile: ""
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 16m
        memory: 244Mi
  settings:
    clusterName: "xquare-v2-cluster"