karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam:::role/KarpenterControllerRole-xquare-v2-cluster"
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 16m
        memory: 244Mi
  settings:
    clusterName: "xquare-v2-cluster"

featureGates:
  spotToSpotConsolidation: true

tolerations:
  - key: "xquare/platform"
    value: "true"
    effect: "NoSchedule"
  - key: "xquare/critical-pods"
    value: "true"
    effect: "NoSchedule"