karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam:::role/KarpenterControllerRole-xquare-v3-cluster"
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 16m
        memory: 244Mi
  settings:
    clusterName: "xquare-v3-cluster"
  tolerations:
    - key: "xquare/critical"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  featureGates:
    spotToSpotConsolidation: false

