infisical:
  infisicalSecret:
    name: xquare-secret
    spec:
      hostAPI: https://app.infisical.com/api
      resyncInterval: 60
      authentication:
        serviceToken:
          serviceTokenSecretReference:
            secretName: infisical-token-secret
            secretNamespace: infisical
          secretsScope:
            envSlug: prod
            secretsPath: "/"
      managedSecretReference:
        secretName: infisical-managed-secret
        secretNamespace: infisical
  backend:
    enabled: true
    kubeSecretRef: "infisical-secret"
  redis:
    enabled: false
  mongodb:
    enabled: false
  ingress:
    enabled: false