provisioner:
  name: xquare-platform
  spec:
    taints:
      - key: "xquare/server"
        value: "true"
        effect: "PreferNoSchedule"
    labels:
      Karpenter: enabled
    kubeletConfiguration:
      maxPods: 110
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: [ "t" ]
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: In
        values: [ "4","8" ]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: [ "3" ]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "spot" ]
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: [ "nitro" ]