nodepools:
  services:
    - name: xquare-platform
      spec:
        taints:
          - key: "xquare/platform"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
          - key: "karpenter.k8s.aws/instance-memory"
            operator: Gt
            values: [ "4096" ]
    - name: xquare-server
      spec:
        taints:
          - key: "xquare/server"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c" ]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
          - key: "node.kubernetes.io/instance-type"
            operator: In
            values: [ "x1e.xlarge" ]
    - name: xquare-test
      spec:
        taints:
          - key: "xquare/test"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c" ]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
    - name: xquare-critical-pods
      spec:
        taints:
          - key: "xquare/critical-pods"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c" ]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
          - key: "karpenter.k8s.aws/instance-memory"
            operator: Gt
            values: [ "2048" ]
    - name: maeumgagym-node
      spec:
        taints:
          - key: "xquare/maeumgagym-node"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c" ]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
          - key: "karpenter.k8s.aws/instance-memory"
            operator: In
            values: [ "4096" ]