nodepools:
  services:
    - name: xquare-platform
      spec:
        taints:
          - key: "xquare/platform"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
    - name: xquare-server
      spec:
        taints:
          - key: "xquare/server"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
    - name: xquare-build-server
      spec:
        taints:
          - key: "xquare/build-server"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
          - key: "karpenter.k8s.aws/instance-memory"
            operator: Gt
            values: [ "7168Mi" ]
    - name: xquare-critical
      spec:
        taints:
          - key: "xquare/critical_service"
            value: "true"
            effect: "NoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "on-demand" ]