nodepools:
  services:
    - name: xquare-platform
      spec:
        taints:
          - key: "xquare/platform"
            value: "true"
            effect: "PreferNoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]
    - name: xquare-service
      spec:
        taints:
          - key: "xquare/service"
            value: "true"
            effect: "PreferNoSchedule"
        labels:
          Karpenter: enabled
        kubeletConfiguration:
          maxPods: 110
        requirements:
          - key: "topology.kubernetes.io/zone"
            operator: In
            values: [ "ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c" ]
          - key: "kubernetes.io/arch"
            operator: In
            values: [ "amd64" ]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: [ "spot" ]
          - key: "karpenter.k8s.aws/instance-hypervisor"
            operator: In
            values: [ "nitro" ]