apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-listen
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["events"]
    verbs: ["watch", "list"]