kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-listener-role-binding
subjects:
  - kind: ServiceAccount
    name: xquare-event-sa
    namespace: xquare-event
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: event-listen
  apiGroup: rbac.authorization.k8s.io