apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: test
    spec:
      tolerations:
        - effect: "NoSchedule"
          key: xquare/test
          operator: "Equal"
          value: "true"
      serviceAccountName: xquare-event-sa
      automountServiceAccountToken: true
      containers:
        - name: nginx
          image: nginx
      nodeSelector:
        karpenter.sh/nodepool: xquare-test-nodepool