apiVersion: apps/v1
kind: Deployment
metadata:
  name: xquare-event-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xquare-event-listener
  template:
    metadata:
      labels:
        app: xquare-event-listener
    spec:
      serviceAccountName: xquare-event-sa
      automountServiceAccountToken: true
      containers:
        - name: xquare-event-listener
          image: 471407337433.dkr.ecr.ap-northeast-2.amazonaws.com/xquare-event-listener-prod:1.4.3