certificates:
  - name: xquare-cert
    commonName: xquare.app
    namespace: istio-system
    dnsNames: 
    - '*.xquare.app'
    - 'xquare.app'
  - name: pick-cert
    commonName: dsm-pick.com
    namespace: istio-system
    dnsNames: 
    - '*.dsm-pick.com'
    - 'dsm-pick.com'
  - name: repo-cert
    commonName: dsm-repo.com
    namespace: istio-system
    dnsNames: 
    - '*.dsm-repo.com'
    - 'dsm-repo.com'
  - name: oidc-proxy-cert
    commonName: xquare.app
    namespace: dex
    dnsNames: 
    - '*.xquare.app'
    - 'xquare.app'
  - name: entrydsm-cert
    commonName: entrydsm.hs.kr
    namespace: istio-system
    dnsNames:
    - '*.entrydsm.hs.kr'
    - 'entrydsm.hs.kr'