tempo-distributed:
  serviceAccount:
    create: true
    name: xquare-tempo
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::786584124104:role/tempo_s3_role
      eks.amazonaws.com/sts-regional-endpoints: "true"
  ingester:
    persistence:
      enabled: true
      size: 10Gi
  traces:
    otlp:
      http:
        enabled: true
        receiverConfig: { }
      grpc:
        enabled: true
        receiverConfig: { }
  storage:
    trace:
      backend: s3
      s3:
        bucket: xquare-tempo
        endpoint: s3.amazonaws.com
        insecure: false
    admin:
      backend: s3
      s3:
        bucket: xquare-tempo
        endpoint: s3.amazonaws.com
        insecure: false
  compactor:
    storage:
      trace:
        backend: s3
        s3:
          bucket: xquare-tempo
          endpoint: s3.amazonaws.com
          insecure: false
