tempo-distributed:
  serviceAccount:
    create: true
    name: xquare-tempo
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::786584124104:role/tempo_s3_role
      eks.amazonaws.com/sts-regional-endpoints: "true"
  querier:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  ingester:
    replicas: 1
    config:
      trace_idle_period: 5s
      flush_check_period: 5s
      max_block_duration: 1m
    persistence:
      enabled: true
      size: 10Gi
    affinity: |
    tolerations:
      - operator: "Exists"
  queryFrontend:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  traces:
    otlp:
      http:
        enabled: true
        receiverConfig: { }
      grpc:
        enabled: true
        receiverConfig: { }
  storage:
    trace:
      backend: s3
      s3:
        bucket: xquare-tempo
        endpoint: s3.amazonaws.com
        insecure: false
    admin:
      backend: s3
      s3:
        bucket: xquare-tempo
        endpoint: s3.amazonaws.com
        insecure: false
  compactor:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
    storage:
      trace:
        backend: s3
        s3:
          bucket: xquare-tempo
          endpoint: s3.amazonaws.com
          insecure: false
  distributor:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
