argo-cd:
  global:
    tolerations:
      - key: "xquare/critical_platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    priorityClassName: system-cluster-critical
  configs:
    params:
      server.insecure: true
    cm:
      url: https://argo-cd.xquare.app
      timeout.reconciliation: 15s
      admin.enabled: true
      exec.enabled: true
      oidc.config: |
        name: dex
        issuer: https://dex.xquare.app
        clientID: argocd
        clientSecret: DIKHZYN1kolN7d6
        requestedScopes: ["openid", "profile", "email", "groups"]
      resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration:
        |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    rbac:
      policy.csv: |
        g, team-xquare:DevOps, role:admin
  applicationSet:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 32Mi
  dex:
    enabled: false
  notifications:
    enabled: false
  redis:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 32Mi
  repoServer:
    ad.datadoghq.com/argocd-repo-server.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "repo_server_endpoint": "http://%%host%%:8084/metrics"
            }
          ]
        }
      }
    name: 'argocd-repo-server'
    resources:
      requests:
        cpu: 500m
        memory: 64Mi
    rbac:
      - verbs: ["get", "list", "watch"]
        apiGroups: [""]
        resources: ["secrets", "configmaps"]

    initContainers:
      - name: download-tools
        image: alpine/curl
        env:
          - name: AVP_VERSION
            value: "1.18.1"
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

    extraContainers:
      - name: avp-helm
        command: ["/var/run/argocd/argocd-cmp-server"]
        image: quay.io/argoproj/argocd:v3.0.5
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /home/argocd/cmp-server/config
            name: cmp-plugin
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
    volumes:
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
      - name: custom-tools
        emptyDir: {}
      - name: tmp-dir
        emptyDir: {}