argo-cd:
  global:
    tolerations:
      - key: "xquare/critical-pods"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    priorityClassName: system-cluster-critical
  configs:
    params:
      server.insecure: true 
    cm:
      url: https://argo-cd.xquare.app
      timeout.reconciliation: 15s
      admin.enabled: true
      exec.enabled: true
      oidc.config: |
        name: dex
        issuer: https://dex.xquare.app
        clientID: argocd
        clientSecret: DIKHZYN1kolN7d6
        requestedScopes: ["openid", "profile", "email", "groups"]
      resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    rbac:
      policy.csv: |
        g, team-xquare:DevOps, role:admin
  applicationSet:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 32Mi
  dex: 
    enabled: false
  notifications:
    enabled: false
  redis:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 32Mi
  repoServer:
    resources:
      requests:
        cpu: 3m
        memory: 64Mi
  controller:
    resources:
      requests:
        cpu: 32m
        memory: 516Mi
  