vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
    affinity: null
  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 15m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/critical_platform
        operator: "Equal"
        value: "true"
    affinity: null
    dataStorage:
      enabled: false
    volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
    volumeMounts:
      - mountPath: "/vault/data"
        name: vault-storage

    extraEnvironmentVars:
      VAULT_SEAL_TYPE: awskms
      AWS_REGION: ap-northeast-2
      VAULT_AWSKMS_SEAL_KEY_ID: alias/vault-auto-unseal-key

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/vault-kms-role"

  pod:
    affinity: null
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  ui:
    affinity: null
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
