vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
    ha:
      enabled: true
      replicas: 2
      raft:
        enabled: true
  pod:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  ui:
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
