vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  server:
    extraVolumes:
      - type: persistentVolumeClaim
        name: vault-data
        path: /vault/data
    extraVolumeMounts:
      - name: vault-data
        mountPath: /vault/file
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/critical-pods
        operator: "Equal"
        value: "true"
  pod:
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  ui:
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
