vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
    affinity: null

  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/critical_platform
        operator: "Equal"
        value: "true"
    affinity: null

    dataStorage:
      enabled: true
      size: 10Gi

    volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: userconfig-vault-seal-config
        secret:
          defaultMode: 420
          secretName: vault-seal-config

    volumeMounts:
      - mountPath: "/vault/data"
        name: vault-storage
      - mountPath: /vault/userconfig/vault-seal-config
        name: userconfig-vault-seal-config
        readOnly: true

    extraArgs: "-config=/vault/userconfig/vault-seal-config/config.hcl"

    extraEnvironmentVars:
      VAULT_SEAL_TYPE: awskms
      AWS_REGION: ap-northeast-2

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "<path:avp/data/aws/vault-kms#role_arn>"

    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
        }
        storage "file" {
          path = "/vault/data"
        }

  pod:
    affinity: null
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"

  ui:
    affinity: null
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
