vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
    affinity: |
  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    tolerations:
      - effect: "NoSchedule"
        key: xquare/critical
        operator: "Equal"
        value: "true"
    affinity: |
    dataStorage:
      enabled: false
  pod:
    affinity: |
    tolerations:
      - effect: "NoSchedule"
        key: xquare/platform
        operator: "Equal"
        value: "true"
  ui:
    affinity: |
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
