vault:
  global:
    injector:
      enabled: true
      resources:
        requests:
          memory: 60Mi
          cpu: 80m
        limits:
          memory: 120Mi
          cpu: 120m

  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 256m

  ui:
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200

# Vault Secret Operator 설정
defaultVaultConnection:
  enabled: true
  address: http://vault-internal.vault.svc.cluster.local:8200
