vault:
  injector:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 80m
      limits:
        memory: 120Mi
        cpu: 120m
  server:
    enabled: true
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
  ui:
    enabled: true
    serviceType: "ClusterIP"
    externalPort: 8200
