name: Check Helm Chart Version

on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get updated chart name and version
        run: |
          git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
            CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
            VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)
            echo "$CHART=$VERSION"

            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHP_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/team-xquare/xquare-infrastructure-global/dispatches \
            -d '{"event_type":"chart-update","client_payload":{"chart": "'$CHART'","version":"'$VERSION'"}}'
          done